app_params:
  env: "local" # dev, prod
  dbsm: "postgres"
sqlite_params:
  storage_path: "./storage/sso.db"
postgres_params:
  user: "postgres"
  host: "localhost"
  port: 5432
  database: "users_db"
  sslmode: "disable"
redis_params:
  host: ""
  port: 6379
  password: ""
  db: 1
kafka_params:
  host: "localhost"
  port: 9092
  topic: "users_topic"
auth_params:
  jwt_ttl_minutes: 60m
  jwt_ttl_refresh_hours: 72h
grpc:
  port: 44044
  timeout: 10h
